### ISSUE TITLE
spf4j-core test failure

### ISSUE THREAD

**Issue by free2create** [zolyfarkas/spf4j#27]
This is based on the master as of 10/09/2018.

Tests run: 10, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 11.863 s <<< FAILURE! - in org.spf4j.base.RuntimeTest
testSomeParams(org.spf4j.base.RuntimeTest)  Time elapsed: 0.242 s  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at org.junit.Assert.assertNotNull(Assert.java:722)
	at org.spf4j.base.RuntimeTest.testSomeParams(RuntimeTest.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)

sure if this is a related Failure but I have see this type of error on separate builds:
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.558 s - in org.spf4j.net.SntpClientTest
2018-10-09T04:03:03.916Z ERROR o.s.b.AbstractRunnable "defaultExecutor1" "Exception in runnable: " 
java.net.BindException:Address already in use (Bind failed)
	at j.n.PlainDatagramSocketImpl.bind0(Native Method)[:1.8.0_181]
	at j.n.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:93)[^]
	at j.n.DatagramSocket.bind(DatagramSocket.java:392)[^]
	at ^.<init>(^:242)[^]
	at ^.<init>(^:299)[^]
	at ^.<init>(^:271)[^]
	at o.s.n.SntpClientTest$1$1.doRun(SntpClientTest.java:116)[test-classes/]
	at o.s.b.AbstractRunnable.run(AbstractRunnable.java:97)[classes/]
	at j.u.c.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_181]
	at j.u.c.FutureTask.run(FutureTask.java:266)[^]
	at o.s.c.LifoThreadPoolExecutorSQP$QueuedThread.execute(LifoThreadPoolExecutorSQP.java:544)[classes/]
	at ^.run(^:464)[^]

**Comment by zolyfarkas** [comment]
You have a "dangling" process from a previous build, Spf4j has some JMX unit tests and starts the unit test process with listening on the TCP JMX port, as such if you have another test still running the test will not start.
