### ISSUE TITLE
junit 5 documentation

### ISSUE THREAD

**Issue by marinier** [zolyfarkas/spf4j#52]
This documentation:

https://github.com/zolyfarkas/spf4j/blob/master/spf4j-slf4j-test/src/site/markdown/index.md

says to use the `spf4j-slf4j-test-junit5` artifact for junit 5 support. However, there does not appear to be such an artifact (at least not on public maven repositories).

Is the documentation out-of-date, or is there some step I'm missing?

**Comment by zolyfarkas** [comment]
@marinier junit 5 support is dev in progress.

if you want to give it a try, you will need to use 8.8.4-SNAPSHOT.
Please give it a try, and report any issues you might stumble upon. 

I am planning to release 8.8.4 this weekend.

**Comment by marinier** [comment]
I just tried 8.8.4, and the dependency gets pulled down correctly. But when I run my test, I get this exception:

```
java.lang.NoClassDefFoundError: org/junit/platform/commons/util/ClassNamePatternFilterUtils
	at org.junit.platform.launcher.core.LauncherFactory.loadAndFilterTestExecutionListeners(LauncherFactory.java:113)
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:99)
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:72)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.<init>(JUnit5TestLoader.java:34)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.createRawTestLoader(RemoteTestRunner.java:371)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.createLoader(RemoteTestRunner.java:366)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.defaultInit(RemoteTestRunner.java:310)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.init(RemoteTestRunner.java:225)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: java.lang.ClassNotFoundException: org.junit.platform.commons.util.ClassNamePatternFilterUtils
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 14 more
```

The strange thing is, I am using junit 5 (jupiter 5.6.2), but if I change the dependency back to just `spf4j-slf4j-test`, then everything works fine (and I don't need to do the maven surefire plugin configuration). I'm running in Eclipse 2020-06, so perhaps Eclipse is interfering somehow.

So, it's working with junit5 as desired as long as I don't use `spf4j-slf4j-test-junit5` (at least in Eclipse 2020-06).

**Comment by marinier** [comment]
I'm actually no longer using this library, so I'm not sure what the final status was.

**Comment by zolyfarkas** [comment]
Thank you, will close, this looks like a missmatch with the junit version eclipse is using.
